2021-06-30 23:37:44,229	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-30 23:37:44,230	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-06-30 23:38:17,393	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-06-30 23:38:17,393	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 01:15:09,019	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 01:15:09,020	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 01:24:27,564	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 01:24:27,564	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.git/config
2021-07-01 01:31:14,736	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 01:31:14,736	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 02:01:27,098	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 02:01:27,098	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-07-01 02:01:27,620	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 02:01:27,621	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 02:29:27,252	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 02:29:27,252	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /owa/
2021-07-01 03:17:54,619	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 03:17:54,619	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 03:39:57,493	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 03:39:57,494	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 03:39:58,353	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 03:39:58,353	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 03:47:28,644	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 03:47:28,644	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /wsman
2021-07-01 03:47:28,776	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 03:47:28,776	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /favicon.ico
2021-07-01 04:13:43,391	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 04:13:43,391	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-07-01 04:13:43,789	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 04:13:43,789	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 04:18:43,857	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: 'api.binance.com'. You may need to add 'api.binance.com' to ALLOWED_HOSTS.
2021-07-01 04:18:43,857	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/v1/time
2021-07-01 04:19:49,225	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 04:19:49,225	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 05:37:15,106	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 05:37:15,106	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 06:21:17,332	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 06:21:17,332	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 06:29:28,175	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 06:29:28,176	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 07:43:14,565	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 07:43:14,566	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021-07-01 07:43:16,078	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 07:43:16,078	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/jsonws/invoke
2021-07-01 07:43:17,657	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 07:43:17,658	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021-07-01 07:43:18,074	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 07:43:18,075	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /index.php
2021-07-01 07:43:24,956	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 07:43:24,957	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /mifs/.;/services/LogService
2021-07-01 07:43:24,969	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 07:43:24,970	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 07:43:28,257	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 07:43:28,258	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /wp-content/plugins/wp-file-manager/readme.txt
2021-07-01 07:43:29,129	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 07:43:29,130	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /console/
2021-07-01 07:43:31,824	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 07:43:31,825	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /Autodiscover/Autodiscover.xml
2021-07-01 07:43:55,827	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 07:43:55,827	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
2021-07-01 08:00:10,312	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: 'api.binance.com'. You may need to add 'api.binance.com' to ALLOWED_HOSTS.
2021-07-01 08:00:10,312	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/v1/time
2021-07-01 08:50:13,787	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 08:50:13,788	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 08:57:02,349	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 08:57:02,349	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 08:57:02,683	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 08:57:02,683	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 08:57:03,742	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 08:57:03,743	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 08:57:08,286	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 08:57:08,286	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /favicon.ico
2021-07-01 08:57:08,890	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: 'ec2-54-248-148-172.ap-northeast-1.compute.amazonaws.com:443'. You may need to add 'ec2-54-248-148-172.ap-northeast-1.compute.amazonaws.com' to ALLOWED_HOSTS.
2021-07-01 08:57:08,890	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 08:57:09,220	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: 'ec2-54-248-148-172.ap-northeast-1.compute.amazonaws.com'. You may need to add 'ec2-54-248-148-172.ap-northeast-1.compute.amazonaws.com' to ALLOWED_HOSTS.
2021-07-01 08:57:09,220	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 08:57:10,262	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 08:57:10,262	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 08:57:14,835	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: 'ec2-54-248-148-172.ap-northeast-1.compute.amazonaws.com'. You may need to add 'ec2-54-248-148-172.ap-northeast-1.compute.amazonaws.com' to ALLOWED_HOSTS.
2021-07-01 08:57:14,835	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /favicon.ico
2021-07-01 08:57:17,425	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 08:57:17,425	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 08:57:22,020	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Not Found: /favicon.ico
2021-07-01 10:47:16,343	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 10:47:16,343	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /epa/scripts/win/nsepa_setup.exe
2021-07-01 11:06:01,670	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 11:06:01,671	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 11:13:07,096	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 11:13:07,097	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 11:46:58,022	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 11:46:58,023	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 12:31:05,578	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 12:31:05,579	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-07-01 12:31:06,113	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 12:31:06,113	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 12:40:26,748	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 12:40:26,748	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /owa/auth/logon.aspx
2021-07-01 13:35:12,688	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 13:35:12,688	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-07-01 13:35:13,267	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 13:35:13,267	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 14:28:11,938	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 14:28:11,938	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 14:59:55,139	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Not Found: /robots.txt
2021-07-01 16:04:21,152	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: 'api.binance.com'. You may need to add 'api.binance.com' to ALLOWED_HOSTS.
2021-07-01 16:04:21,152	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/v1/time
2021-07-01 17:47:43,998	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 17:47:43,999	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 18:31:03,133	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 18:31:03,134	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 18:33:22,225	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 18:33:22,225	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /owa/auth/logon.aspx
2021-07-01 18:49:41,456	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 18:49:41,456	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /actuator/health
2021-07-01 19:23:39,065	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: 'api.binance.com'. You may need to add 'api.binance.com' to ALLOWED_HOSTS.
2021-07-01 19:23:39,065	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/v1/time
2021-07-01 19:34:47,419	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 19:34:47,419	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 20:01:43,405	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 20:01:43,405	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-07-01 20:01:44,975	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 20:01:44,976	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 20:25:09,555	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 20:25:09,555	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-07-01 20:25:11,133	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 20:25:11,133	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 20:30:44,174	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 20:30:44,174	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /api/jsonws/invoke
2021-07-01 20:30:45,164	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 20:30:45,164	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021-07-01 20:30:50,925	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 20:30:50,926	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /index.php
2021-07-01 20:30:51,863	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 20:30:51,863	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021-07-01 20:30:56,658	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 20:30:56,658	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /mifs/.;/services/LogService
2021-07-01 20:30:59,244	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172:443'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 20:30:59,245	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 21:31:25,974	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 21:31:25,974	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /.env
2021-07-01 21:31:26,646	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 21:31:26,646	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 21:51:53,464	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 21:51:53,464	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 21:51:55,904	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 21:51:55,904	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 22:15:49,529	[INFO]	/home/labolibrary_admin/venv_labolibrary/labolibrary/search/views.py(Line:69)	<QueryDict: {'search_text': [''], 'university_area': [''], 'university': [''], 'faculty': [''], 'department': [''], 'professor_name': [''], 'master_acceptance': ['unknown'], 'doctor_acceptance': ['unknown'], 'csrfmiddlewaretoken': ['oHR97n35BCnXyf9DCvpEo1R18lyOVgoIOUUt1b8hQ7LXfUX2KtMJKaDZ4Bx1BFON']}>
2021-07-01 22:50:03,698	[INFO]	/home/labolibrary_admin/venv_labolibrary/labolibrary/search/views.py(Line:69)	<QueryDict: {'search_text': ['レーザー'], 'university_area': [''], 'university': ['1'], 'faculty': ['209'], 'department': ['15'], 'professor_name': [''], 'master_acceptance': ['unknown'], 'doctor_acceptance': ['unknown'], 'csrfmiddlewaretoken': ['7vWSuf0hDzZwAJZdoq6PDJC3hkSAZIL0xIZco35tS4nwhoNCwotUZSo1dARNF7b5']}>
2021-07-01 22:53:53,802	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Not Found: /favicon.ico
2021-07-01 22:57:06,349	[ERROR]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/core/handlers/exception.py(Line:101)	Invalid HTTP_HOST header: '54.248.148.172'. You may need to add '54.248.148.172' to ALLOWED_HOSTS.
2021-07-01 22:57:06,349	[WARNING]	/home/labolibrary_admin/venv_labolibrary/lib64/python3.7/site-packages/django/utils/log.py(Line:230)	Bad Request: /
2021-07-01 22:57:29,532	[INFO]	/home/labolibrary_admin/venv_labolibrary/labolibrary/search/views.py(Line:69)	<QueryDict: {'search_text': ['長谷川'], 'university_area': [''], 'university': [''], 'faculty': [''], 'department': [''], 'professor_name': [''], 'master_acceptance': ['unknown'], 'doctor_acceptance': ['unknown'], 'csrfmiddlewaretoken': ['490gD00MP1po9RlAoq1350cQLWqM2Sx8um3AxO5Y4wNoQw9Zwoo8r9YOHcpZIhXd']}>
2021-07-01 22:57:40,156	[INFO]	/home/labolibrary_admin/venv_labolibrary/labolibrary/search/views.py(Line:69)	<QueryDict: {'search_text': [''], 'university_area': [''], 'university': [''], 'faculty': [''], 'department': [''], 'professor_name': ['長谷川'], 'master_acceptance': ['unknown'], 'doctor_acceptance': ['unknown'], 'csrfmiddlewaretoken': ['nNDfTRJQRqnTDIViBGVFVgVhhoich5NLN0GzNFO26VLTknJHJEiKhpHfdEhpXudQ']}>
